/*
 * generated by Xtext 2.15.0
 */
package de.itemis.jmhmathexample


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathDSLStandaloneSetup extends MathDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MathDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
